### ISSUE TITLE
Timothy Stanton base and base AI glitchy

### ISSUE THREAD

**Issue by scovelme** [LAX1DUDE/LAXATIVEMODS#3]
From what I have found the base will frequently regenerate itself and I believe spawns new Timothy Stantons, this not only suffocates some of them because they are inside stuff, it also messes up their AI, as they no longer attack other creatures in their base after this regeneration. pls fix m80

**Comment by LAX1DUDE** [comment]
I checked it and it's all fine.

You forgot to set up a static uuid and username in the run config
